# Base configuration

# use docker-compose.override.yaml for local overrides
# The .env file contains the variables referenced such aus ${DATABASE_URL}

version: '3.7'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      DATABASE_HOST: postgresdb
    ports:
      - 3000:3000
    networks:
      - advice-network
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-pass
      POSTGRES_USER: admin
      POSTGRES_DB: adviceapp
    secrets:
      - db-pass
    networks:
      - advice-network
    volumes:
      - db-data:/var/lib/postgresql/data

# Define secrets in the override file for your system, e.g.:
# secrets:
#  db-pass:
#    file: docker/secrets/db-pass.txt

volumes:
  db-data:

networks:
  advice-network:
